from enum import Enum
from typing import Dict


class ServiceCallStatus(str, Enum):
    SCS_OK = "SCS_OK"
    SCS_ANYMAL_UNKNOWN = "SCS_ANYMAL_UNKNOWN"
    SCS_ANYMAL_OFFLINE = "SCS_ANYMAL_OFFLINE"
    SCS_ERROR_UNKNOWN = "SCS_ERROR_UNKNOWN"
    UNRECOGNIZED = "UNRECOGNIZED"


class ANYmalServiceCallStatus(str, Enum):
    ASCS_UNDEFINED = "ASCS_UNDEFINED"
    ASCS_OK = "ASCS_OK"
    ASCS_ERROR_ANYMAL_UNKNOWN = "ASCS_ERROR_ANYMAL_UNKNOWN"
    ASCS_ERROR_ANYMAL_OFFLINE = "ASCS_ERROR_ANYMAL_OFFLINE"
    ASCS_ERROR_PERMISSION = "ASCS_ERROR_PERMISSION"
    ASCS_ERROR_UNKNOWN = "ASCS_ERROR_UNKNOWN"
    UNRECOGNIZED = "UNRECOGNIZED"


class UserInteractionMode(str, Enum):
    UIM_UNDEFINED = "UIM_UNDEFINED"
    UIM_AUTONOMOUS = "UIM_AUTONOMOUS"
    UIM_MANUAL = "UIM_MANUAL"
    UIM_MANUAL_RCU = "UIM_MANUAL_RCU"
    UIM_AUTONOMOUS_REACTION = "UIM_AUTONOMOUS_REACTION"
    UNRECOGNIZED = "UNRECOGNIZED"


class ControlMissionStatus(str, Enum):
    CMS_UNDEFINED = "CMS_UNDEFINED"
    CMS_OK = "CMS_OK"
    CMS_ERROR_REQUEST_INVALID = "CMS_ERROR_REQUEST_INVALID"
    CMS_ERROR_MISSION_UNKNOWN = "CMS_ERROR_MISSION_UNKNOWN"
    CMS_ERROR_PROTECTIVE_STOP_ENABLED = "CMS_ERROR_PROTECTIVE_STOP_ENABLED"
    CMS_ERROR_POWER_CUT_ENABLED = "CMS_ERROR_POWER_CUT_ENABLED"
    CMS_ERROR_CONTROL_LEASE_UNOWNED = "CMS_ERROR_CONTROL_LEASE_UNOWNED"
    CMS_ERROR_MANUAL_MODE = "CMS_ERROR_MANUAL_MODE"
    CMS_ERROR_NO_MISSION = "CMS_ERROR_NO_MISSION"
    CMS_ERROR_MISSION_PAUSED = "CMS_ERROR_MISSION_PAUSED"
    CMS_ERROR_MISSION_EXECUTING = "CMS_ERROR_MISSION_EXECUTING"
    CMS_ERROR_UNKNOWN = "CMS_ERROR_UNKNOWN"
    UNRECOGNIZED = "UNRECOGNIZED"


class BatteryStatus(str, Enum):
    BS_UNKNOWN = "BS_UNKNOWN"
    BS_CHARGING = "BS_CHARGING"
    BS_DISCHARGING = "BS_DISCHARGING"
    BS_NOT_CONNECTED = "BS_NOT_CONNECTED"
    BS_ERROR = "BS_ERROR"
    BS_PERMANENT_FAILURE = "BS_PERMANENT_FAILURE"
    UNRECOGNIZED = "UNRECOGNIZED"


BATTERY_STATUS_TO_INTEGER_MAPPING: Dict[BatteryStatus, int] = {
    BatteryStatus.BS_UNKNOWN: 0,
    BatteryStatus.BS_CHARGING: 1,
    BatteryStatus.BS_DISCHARGING: 2,
    BatteryStatus.BS_NOT_CONNECTED: 3,
    BatteryStatus.BS_ERROR: 4,
    BatteryStatus.BS_PERMANENT_FAILURE: 5,
}


class ClientType(str, Enum):
    CLCT_ON_SITE = "CLCT_ON_SITE"
    CLCT_REMOTE = "CLCT_REMOTE"
    CLCT_AUTOMATED = "CLCT_AUTOMATED"
    UNRECOGNIZED = "UNRECOGNIZED"


class ProtectiveStopOrigin(str, Enum):
    PSO_UNSET = "PSO_UNSET"
    PSO_SOFTWARE = "PSO_SOFTWARE"
    PSO_RCU = "PSO_RCU"
    PSO_GUI = "PSO_GUI"
    UNRECOGNIZED = "UNRECOGNIZED"


class MissionType(str, Enum):
    MT_PREDEFINED = "MT_PREDEFINED"
    MT_AD_HOC = "MT_AD_HOC"
    UNRECOGNIZED = "UNRECOGNIZED"


class ANYmalMissionStatus(str, Enum):
    MS_NA = "MS_NA"
    MS_RUNNING = "MS_RUNNING"
    MS_PAUSED = "MS_PAUSED"
    MS_COMPLETED = "MS_COMPLETED"
    UNRECOGNIZED = "UNRECOGNIZED"


class ANYmalTaskStatus(str, Enum):
    TS_NA = "TS_NA"
    TS_UPCOMING = "TS_UPCOMING"
    TS_ONGOING = "TS_ONGOING"
    TS_PREEMPTED = "TS_PREEMPTED"
    TS_COMPLETED = "TS_COMPLETED"
    UNRECOGNIZED = "UNRECOGNIZED"


class Outcome(str, Enum):
    OC_NA = "OC_NA"
    OC_SUCCESS = "OC_SUCCESS"
    OC_FAILURE = "OC_FAILURE"
    OC_NORMAL = "OC_NORMAL"
    OC_ANOMALY = "OC_ANOMALY"
    UNRECOGNIZED = "UNRECOGNIZED"


class ResultInterpretation(str, Enum):
    RI_NA = "RI_NA"
    RI_NORMAL = "RI_NORMAL"
    RI_ANOMALY = "RI_ANOMALY"
    RI_NOT_DETECTED = "RI_NOT_DETECTED"
    UNRECOGNIZED = "UNRECOGNIZED"


class InspectionMeasurementType(str, Enum):
    IMT_UNDEFINED = "IMT_UNDEFINED"
    IMT_THERMAL = "IMT_THERMAL"
    IMT_VISUAL = "IMT_VISUAL"
    IMT_AUDITIVE = "IMT_AUDITIVE"
    IMT_VIDEO = "IMT_VIDEO"
    IMT_CONCENTRATION = "IMT_CONCENTRATION"
    IMT_CONCENTRATION_MONITORING = "IMT_CONCENTRATION_MONITORING"
    IMT_ACOUSTIC_IMAGE = "IMT_ACOUSTIC_IMAGE"
    IMT_CUSTOM = "IMT_CUSTOM"
    UNRECOGNIZED = "UNRECOGNIZED"


class InspectionInterpretationType(str, Enum):
    IIT_UNDEFINED = "IIT_UNDEFINED"
    IIT_THERMAL_FRAME_CAPTURE = "IIT_THERMAL_FRAME_CAPTURE"
    IIT_THERMAL_HOTSPOT_DETECTION = "IIT_THERMAL_HOTSPOT_DETECTION"
    IIT_VISUAL_FRAME_CAPTURE = "IIT_VISUAL_FRAME_CAPTURE"
    IIT_VISUAL_READOUT = "IIT_VISUAL_READOUT"
    IIT_VISUAL_OBJECT_DETECTION = "IIT_VISUAL_OBJECT_DETECTION"
    IIT_AUDITIVE_SAMPLE_CAPTURE = "IIT_AUDITIVE_SAMPLE_CAPTURE"
    IIT_AUDITIVE_FREQUENCY_ANALYSIS = "IIT_AUDITIVE_FREQUENCY_ANALYSIS"
    IIT_ACOUSTIC_IMAGE_FRAME_CAPTURE = "IIT_ACOUSTIC_IMAGE_FRAME_CAPTURE"
    IIT_LEAK_DETECTION = "IIT_LEAK_DETECTION"
    IIT_PARTIAL_DISCHARGE_DETECTION = "IIT_PARTIAL_DISCHARGE_DETECTION"
    IIT_MECHANICAL_INSPECTION = "IIT_MECHANICAL_INSPECTION"
    IIT_VIDEO = "IIT_VIDEO"
    IIT_CUSTOM = "IIT_CUSTOM"
    IIT_CONCENTRATION = "IIT_CONCENTRATION"
    UNRECOGNIZED = "UNRECOGNIZED"


class MeasuredTemperatureType(str, Enum):
    MTT_MIN = "MTT_MIN"
    MTT_MAX = "MTT_MAX"
    MTT_SPOT = "MTT_SPOT"
    UNRECOGNIZED = "UNRECOGNIZED"


class SubstanceConcentrationLevel(str, Enum):
    SCL_NA = "SCL_NA"
    SCL_NOT_ENOUGH_MEASUREMENTS = "SCL_NOT_ENOUGH_MEASUREMENTS"
    SCL_NORMAL = "SCL_NORMAL"
    SCL_LOW_ALARM = "SCL_LOW_ALARM"
    SCL_LOW_WARNING = "SCL_LOW_WARNING"
    SCL_HIGH_WARNING = "SCL_HIGH_WARNING"
    SCL_HIGH_ALARM = "SCL_HIGH_ALARM"
    UNRECOGNIZED = "UNRECOGNIZED"


class InterpretationConfidenceLevel(str, Enum):
    ICL_NA = "ICL_NA"
    ICL_LOW = "ICL_LOW"
    ICL_HIGH = "ICL_HIGH"
    UNRECOGNIZED = "UNRECOGNIZED"
